name: Normal Check Flats Availability

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 5 PM UTC (12 PM Chicago time)
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grant write access to the repository contents

jobs:
  check_flats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python check_flats.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update available flats in README.md'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
